[workspace]
members=[
  "auction/program",
  "auction-house/program",
  "gumdrop/program",
  "metaplex/program",
  "token-entangler/program",
  "token-vault/program",
  "token-vault/test",
  "nft-packs/program",
  "membership-token/program"
]
exclude = [
  "membership-token/cli",
  "token-metadata",
  "candy-machine/program"
]
