name: SDK Metaplex

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          code:
            - 'metaplex/**'
            - 'nft-packs/**'
  build-lint-and-test-metaplex:
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/yarn-install-and-verify
        with: 
          cache_id: sdk-metaplex
          working_dir: ./metaplex/js
          build_auction: true
          build_token_vault: true
          build_token_metadata: true
